### PR TITLE
Fix OSX setup

### PR DESCRIPTION
**Pull request by hadim**
Ping @KeyWeeUsr.

In the OSX if statement `JRE_HOME` is not defined.

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
@hadim Could you also add a travis build for OSX with java 8 and java 9+? You can check the matrix at [plyer `.travis.yml`](https://github.com/kivy/plyer/blob/master/.travis.yml).

**Comment by KeyWeeUsr** [comment]
To test it quickly you can temporarily remove linux from the matrix and various python versions e.g. just keep osx 2.7 and 3.7 for java 8 and java 9. What I think is happening is this: https://github.com/kivy/pyjnius/issues/304#issue-266756833 i.e. a missing `jre` folder for Java 8. If you do `ls -lah` for particular folders in the CI job, you'll get there :)

**Comment by hadim** [comment]
I am already working on the conda forge feedstock. Could you take care of this one?

**Comment by hadim** [comment]
The `Allow edits from maintainers.` box is checked.

**Comment by hadim** [comment]
@KeyWeeUsr I have disabled Java 8/OSX build on Travis. Can you merge and I'll try to submit a new PR later this week if you cannot do it.

**Comment by KeyWeeUsr** [comment]
I took a look at it and I believe https://github.com/kivy/pyjnius/pull/364/files#diff-2eeaed663bd0d25b7e608891384b7298R124 is the mistake in here if you use `conda`. I have no experience with `conda`, so you'll have more luck with it, since the original fix is yours. You might try to install Java 8 the ordinary way, without `conda`.

**Comment by hadim** [comment]
Yes finally. Hope you'll release a new version soon!

**Pull request merged**
