### PR TITLE
Add support for other include paths on other targets

### PR DESCRIPTION
**Pull request by thopiekar**
Will look at the jre_home to determinate which str() is needed for the variable, called "cpu".

### CODE REVIEW

**Comment by akshayaurora** [comment]
@thopiekar hey would it be possible to rebase this ?

**Comment by dessant** [comment]
@thopiekar :pager:

**Comment by thopiekar** [comment]
Oh, sorry, yes I can take a look on this later. As far as I remember it was
because of the problem that armhf builds fail on launchpad.
Am 03.11.2015 13:01 schrieb "dessant" <notifications@github.com>:

**Comment by dessant** [comment]
@thopiekar thanks, no rush :-P

**Comment by thopiekar** [comment]
No problem. I even forget that I ever coded this. :D

**Comment by thopiekar** [comment]
I just rebased this PR, while handling the problem another way. Hope you agree with that.

**Comment by tito** [comment]
I wonder how this works with your recent #184

**Comment by thopiekar** [comment]
#184 is merged and built in daily PPA. Closing this old request ;)

**Pull request closed without merging**
