### PR TITLE
setup fixes for python 3.5

### PR DESCRIPTION
**Pull request by danielepantaleone**
This PR fixes an issue that arises when building under python 3.5.

### CODE REVIEW

**Comment by danielepantaleone** [comment]
Any chance for this to get merged?

**Comment by inclement** [comment]
Thanks, and sorry for the delay. I've added pyjnius to my notifications to try and catch these things, so hopefully there won't be such a delay in the future.

**Comment by danielepantaleone** [comment]
No worries :smile: I just wanted to know if it was going to be refused because I'm currently installing PyJNIus from my custom fork and it's a pain to rebase every time something new gets included in the official repo :+1:

**Comment by tychovk** [comment]
Necroing, but: does/should it work for python 3.5 now?

**Comment by inclement** [comment]
Yes, it should just work.

**Comment by tychovk** [comment]
hmm so from the bottom up, these are my steps:
https://kivy.org/docs/installation/installation.html#ubuntu (which btw still states that `In addition, you need a Python 2.x (2.7 <= x < 3.0) or 3.x (3.3 <= x) interpreter.)
```
$ sudo apt-get install python-setuptools python-pygame python-opengl \
  python-gst0.10 python-enchant gstreamer0.10-plugins-good python-dev \
  build-essential libgl1-mesa-dev libgles2-mesa-dev zlib1g-dev python-pip
```
then:
pip3 install kivy
It says:
```
successfully built kivy
```
Yay!

**Pull request merged**
