### PR TITLE
add missing architecture for python setup in actions

### PR DESCRIPTION
**Pull request by tshirtman**

### CODE REVIEW

**Review by cmacdonald — APPROVED** [review]
LGTM

**Comment by cmacdonald** [comment]
Windows is failing on this, both x64 and x86, e.g.
https://github.com/kivy/pyjnius/runs/1283042170?check_suite_focus=true#step:8:48
but then pytest completes normally?

```
============================= test session starts =============================
platform win32 -- Python 3.6.8, pytest-6.1.1, py-1.9.0, pluggy-0.13.1 -- c:\hostedtoolcache\windows\python\3.6.8\x86\python.exe
cachedir: .pytest_cache
rootdir: D:\a\pyjnius\pyjnius
plugins: cov-2.10.1, rerunfailures-9.1.1
Windows fatal exception: access violation

Current thread 0x000006b0 (most recent call first):
  File "c:\hostedtoolcache\windows\python\3.6.8\x86\lib\site-packages\six.py", line 856 in __new__
  File "c:\hostedtoolcache\windows\python\3.6.8\x86\lib\site-packages\jnius\reflect.py", line 20 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "c:\hostedtoolcache\windows\python\3.6.8\x86\lib\site-packages\jnius\__init__.py", line 42 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "D:\a\pyjnius\pyjnius\tests\test_arraylist.py", line 3 in <module>
  File "c:\hostedtoolcache\windows\python\3.6.8\x86\lib\site-packages\_pytest\assertion\rewrite.py", line 171 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 994 in _gcd_import
  <snip>
```

**Comment by tshirtman** [comment]
It's really weird that it completes successfully after seemingly indicating a crash (segfault?) indeed :|

**Comment by tshirtman** [comment]
Merging, we can open an issue to investigate that, i think it's still progress.

**Pull request merged**
