### PR TITLE
fix bug for constuctors with variable arguments

### PR DESCRIPTION
**Pull request by hx2A**
This is a fix for #562 

Simple fix so that `calculate_score` works for constructors the way it works for methods.

### CODE REVIEW

**Comment by cmacdonald** [comment]
Good spot Jim. I realise that while I recently improved the error messages for methods,
c.f. https://github.com/kivy/pyjnius/blob/master/jnius/jnius_export_class.pxi#L341
I didnt do likewise here:
https://github.com/kivy/pyjnius/blob/master/jnius/jnius_export_class.pxi#L1143

Could we fix that too?

**Review by tshirtman — APPROVED** [review]
Nice catch!

**Comment by hx2A** [comment]
@tshirtman thanks!

I just added to the PR to improve the error message, as per @cmacdonald 's suggestion. Example error is below. Is it possible to further improve this to also say the class name (like the similar error message for methods)? Would that even be useful?

```
In [7]: String = jnius.autoclass('java.lang.String')

In [8]: String(1, 2, 3, 'asdfasdf')
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-8-327bc0e8194d> in <module>
----> 1 String(1, 2, 3, 'asdfasdf')

~/Projects/ITP/pythonprocessing/pyjnius/jnius/jnius_export_class.pxi in jnius.JavaClass.__init__()
    268 
    269         if 'noinstance' not in kwargs:
--> 270             self.call_constructor(args, kwargs)
    271             self.resolve_methods()
    272             self.resolve_fields()

~/Projects/ITP/pythonprocessing/pyjnius/jnius/jnius_export_class.pxi in jnius.JavaClass.call_constructor()
    338                 )
    339             if not scores:
--> 340                 raise JavaException(
    341                     'No constructor matching your arguments, requested: {}, available: {}'.format(
    342                         args,

JavaException: No constructor matching your arguments, requested: (1, 2, 3, 'asdfasdf'), available: ['([B)V', '([BII)V', '([BLjava/nio/charset/Charset;)V', '([BLjava/lang/String;)V', '([BIILjava/nio/charset/Charset;)V', '(Ljava/lang/StringBuilder;)V', '(Ljava/lang/StringBuffer;)V', '([CII)V', '([C)V', '(Ljava/lang/String;)V', '()V', '([BIILjava/lang/String;)V', '([BI)V', '([BIII)V', '([III)V']
```

**Comment by hx2A** [comment]
I just added an additional fix for signature hints on constructors with variable arguments. Previously there was an assert statement that forbid the use of signature hints on constructors with variable arguments.

**Comment by tshirtman** [comment]
> Example error is below. Is it possible to further improve this to also say the class name (like the similar error message for methods)? Would that even be useful?

i think you can use `self.__javaclass__` ? and yes, that would certainly be an improvement.

**Comment by hx2A** [comment]
@tshirtman that worked

**Review by tshirtman — APPROVED** [review]

**Pull request merged**
