### PR TITLE
fix: readme reflecting right fragment about java.lang.String

### PR DESCRIPTION
**Pull request by akkumar**
The example needs explicit instantiation of java.lang.String , at least with Java8. 

So - needs to be modified per se.

### CODE REVIEW

**Comment by Arnie97** [comment]
At least not so on my PC. Anyone else got this bug?

```
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> from jnius import autoclass
>>> System = autoclass('java.lang.System')
>>> System.getProperties().get('java.version')
'1.8.0_152-release'
>>> Stack = autoclass('java.util.Stack')
>>> stack = Stack()
>>> stack.push('hello')
'hello'
>>> stack.push('world')
'world'
>>> print(stack.pop())
world
>>> print(stack.pop())
hello
```

**Comment by Arnie97** [comment]
Are you trying to provide a workaround for #300?

**Comment by akkumar** [comment]
@Arnie97 - That sounds about right regarding issue with cython. 

Yes - I was using Cython==0.27.3. Reproducible with Cython==0.28.2 as well. (with python 3.6.5 )

```bash
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

For what it is worth - here is 
```python
>>> from jnius import autoclass
>>> System = autoclass('java.lang.System')
>>> System.getProperties().get('java.version')
None
```

**Comment by akkumar** [comment]
Given that a workaround exists as suggested by @Arnie97 - closing it hence. 

Now - it would be great to have a release with the patch though.

**Pull request closed without merging**
