### PR TITLE
Switching to JNI UTF-16 API for strings to fix supplementary unicode char encoding

### PR DESCRIPTION
**Pull request by brandonherzog**
Fix for #284

Switched all string creation/decoding to use the JNI UTF-16 api for unicode rather than try to wrangle with JNI's modified UTF-8 encoding.

I kept the existing assumption for Python 2 that byte strings are UTF-8 encoded.

### CODE REVIEW

**Comment by wavenator** [comment]
Can you please review and merge this PR. This is really urgent. Current pujnius version with latest Cython version does not work at all with strings.

**Comment by drmoose** [comment]
There's ample evidence to support the hypothesis that this project is abandoned. I've got a [fork](https://github.com/drmoose/pyjnius.git) which merges this and my two PRs to get something semi-usable, which is pip-installable via

```
pip install --upgrade git+https://github.com/drmoose/pyjnius.git
```

I make no guarantees that my fork will be any better for your purposes than the official version, but it's working for my company for now. Unfortunately, I do not have the time to do proper maintenance and support on a project of this scale and complexity, so you're kinda on your own if it doesn't help.

I mention it here for @wavenator and anybody else who comes looking for a way to get pyjnius working on a modern OS, in the hopes that it may get you closer to something usable.

**Comment by g-bon** [comment]
I second @wavenator , this would be great to have merged sooner than later if possible because it's a blocker with latest cython. @inclement mentioning you just to make this pop in your inbox because it appears you have been the most active maintainer lately, but I understand and respect that this is pro bono work make on free time.

**Comment by tito** [comment]
@drmoose There is a difference between abandonned project and struggle to handle work on all the kivy project. We're open to maintainer, if you want to step up, don't hesitate.

**Comment by g-bon** [comment]
@tito you legend. I appreciate A LOT.

**Comment by drmoose** [comment]
@tito I misinterpreted an [earlier comment from inclement](https://github.com/kivy/pyjnius/pull/299#issuecomment-337995441), then. Sorry for that, and thanks a ton for making the time to review PRs here.

**Comment by brandonherzog** [comment]
Awesome, thanks @tito!

**Comment by wavenator** [comment]
@tito I really appreciate your work. Thanks a lot for the merge!

**Comment by akkumar** [comment]
@tito  - Can we look forward to a release with this PR ? That would be immensely useful as we work with later versions of cython.

**Comment by KeyWeeUsr** [comment]
@akkumar There has already been a new release since, please check it out. `1.4.1` is going to be released soon-ish too.

**Pull request merged**
