### PR TITLE
Make this work with python 3.4 as well as 2.7

### PR DESCRIPTION
**Pull request by benson-basis**
Also use dlopen on Mac and Linux, and clean up a number of other things.

### CODE REVIEW

**Comment by tshirtman** [comment]
This seems to fix/touch a wide range of things, and there are multiple "fixup" commits, it would be better to separate it in different PRs and squashing the fixups in the relevant commits. Are you familiar enough with git for that?

Thanks for your contribution!

**Comment by benson-basis** [comment]
Two of the extra things are in two PR's that I submitted before; if you merge those, this will get smaller. Once you do that, I'm happy to sort out the dlopen and other non-3.4 changes into more commits/PRs.  I submitted this to see if anyone was paying attention :-).

**Comment by haricot** [comment]
[Build Status](https://travis-ci.org/haricot/pyjnius)

**Comment by dessant** [comment]
@tito plop

**Comment by tito** [comment]
@dessant feel free to handle the maintenance (pr and merge) :)

**Comment by dessant** [comment]
@benson-basis please rebase and i'll merge right away if it passes py3 tests.

**Comment by benson-basis** [comment]
I merged; it passes 'make tests PYTHON3=1' for me --- on my mac. I haven't
tried anything on Linux.

**Comment by dessant** [comment]
It seems to fail both with py2 and 3 on linux.

**Comment by benson-basis** [comment]
I'll start up a VM and sort it.

**Comment by dessant** [comment]
@benson-basis thanks a bunch for taking care of this, and sorry for the long silence.

This project is in great need of a maintainer, if you would like to contribute beyond this pr, we would be glad to give you access.

**Comment by benson-basis** [comment]
Hmm. On my linux VM, the python2 test worked once I pip installed future.
I'm struggling to get cython to install on that box.

As for the future, I did all this work when I had a problem that it solved.
I'm not so sure now if I still have that problem, I'll let you know.

**Comment by benson-basis** [comment]
@dessant Looks like I cured what ailed it.

**Comment by dessant** [comment]
@benson-basis, awesome work, thanks again!

**Comment by dessant** [comment]
Some users are reporting failed installations and apk packaging also seems to fail after the merge. @benson-basis, @haricot were you able to build an apk with your branches?

A different problem is the usage of future, which is a ~ 1.6 MB package, this makes it a bit heavy for Android deployment. A better alternative could be six.

These issues must be sorted out quickly because buildozer uses pyjnius master, so this is reaching and breaking things for many people. The other option is to revert the pr.

**Comment by benson-basis** [comment]
@dessant I don't know anything about apks. I don't know how to build one -- I don't even know if I have the tools to build one on any of my systems. Can you give me a hint? If you need to revert on master, how about you go ahead and add bimargulies (not this account) so I can maintain a branch until this sorts out?

**Comment by benson-basis** [comment]
The android install instructions don't seem believable to me. They don't mention the NDK at all.

**Comment by Kovak** [comment]
http://python-for-android.readthedocs.org/en/latest/quickstart/#dependencies

**Comment by benson-basis** [comment]
@dessant @Kovak  I'm sorry to be sense, but how does python-for-android invoke setup.py? The doc here says to run distribute.sh, but no such script is in the repo.

**Comment by dessant** [comment]
I would be in favor of trying to fix master before resorting to keeping a separate branch. I see you've already taken steps to clean up master. Did the p4a docs help in the end? I don't have experience with android, but @inclement should be able to give you feedback.

**Comment by benson-basis** [comment]
The docs were, in the end, enough of a hint. I still think someone forgot
to commit that shell script.

Until I know the precise p-f-a command that the other folks need to work, I
can't verify that it works. So far, all I know is that 'create' works.

**Comment by dessant** [comment]
distribute.sh is part of the old p4a toolchain, it should not be needed for the guide linked above.
If create succeeded, you should have an apk somewhere.

**Comment by benson-basis** [comment]
I don't think that create makes apks. The doc says that apks are a separate
process, and require additional arguments.

Can someone who is trying to consume this stuff chime in and say what,
exactly, they do with p-f-a?

**Comment by inclement** [comment]
Yeah, the `create` command only makes an android dist, but this should be enough to test that pyjnius compiles. You can use the `apk` command afterwards to make an apk from this dist.

**Comment by benson-basis** [comment]
I would like to know _how_ the consumers of this package use the apk
command so I can repro what they do.

**Comment by inclement** [comment]
Mostly they probably don't, most people build apks will be using buildozer which uses the older python-for-android toolchain (with distribute.sh as noted above).

However, this should be identical to running a new-p4a command like:

    p4a apk --requirements=kivy,sdl2 --private /home/asandy/devel/python-for-android/tests/testapp --package=net.inclem.sdl2 --name=sdl2 --version=0.6 --debug

**Comment by benson-basis** [comment]
That commands fails with a problem that isn't accessible to me:

RAN: '/usr/bin/patch -t -d
/home/benson/.local/share/python-for-android/build/other_builds/pyjnius-sdl2/armeabi/pyjnius
-p1 -i
/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch'


  STDOUT:
patching file jnius/jnius_jvm_android.pxi
patching file setup.py
Hunk #1 FAILED at 41.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej

Please fix the android pxi file to be correct as checked in, since I can't
patch your patch.

**Comment by inclement** [comment]
The patch was broken by the recent changes to pyjnius, I've pushed an updated on to python-for-android master.

**Pull request merged**
