### PR TITLE
Add BSD Unix build support (FreeBSD, OpenBSD, NetBSD, ..).

### PR DESCRIPTION
**Pull request by cederom**
* Builds fine on FreeBSD.
* OpenBSD returns build errors on `build_ext()` call.

Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>

### CODE REVIEW

**Review by tshirtman — APPROVED** [review]
Looks good to me, wondering if the "in bsd" test might be casting too wide a net, but can’t think of any platform that would be impacted, so that’s probably just fine.

**Comment by cederom** [comment]
Thank you @tshirtman :-)

This is the initial patch to add build support for all BSD. I am working on FreeBSD and this enables build and install :-) It may need some tuning for other BSD flavors (like OpenBSD, NetBSD, NomadBSD, MidnightBSD, etc) but the road is open now :-)

`sys.platform` returns `freebsd13` on my FreeBSD desktop and `openbsd71` on OpenBSD thus `bsd` only check and removal of the release number :-)

I have created OpenBSD VM just to verify. It fails on extension built telling me that `.xpi` file is unknown. If you have some spare time we can track this issue now and fix.. or leave it for some OpenBSD users when interest shows up? Up to You :-)

**Comment by tshirtman** [comment]
No reason to block it, it can be improved later when interrest shows up indeed :).

Thanks!

**Comment by cederom** [comment]
Thank you @tshirtman :-)

Allright, OpenBSD build problem was caused by missing `cython` package, after `pip install cython` inside virtualenv build goes fine :-)

Maybe we could add `requirements.txt` file with all (venv) python modules required for development? :-)

**Comment by tshirtman** [comment]
Cython is declared as a build dependency in pyproject.toml, so if the build is done in a standard way (we use cibuildwheels in the github action), then it should be installed in the build virtualenv.

How did you build it?

**Pull request merged**
